In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
x_data = np.linspace(0,10,1000000)
noise = np.random.randn(len(x_data))
# y = mx + b + noise_levels
b = 5

y_real =  (0.5 * x_data ) + 5 + noise

In [3]:
x_data

array([0.000000e+00, 1.000001e-05, 2.000002e-05, ..., 9.999980e+00,
       9.999990e+00, 1.000000e+01])

In [4]:
y_real

array([ 5.33310419,  5.7422955 ,  4.04552322, ..., 10.21228132,
        8.81018439,  9.68055752])

In [5]:
ft_columns = [tf.feature_column.numeric_column("x",shape=[1])]

In [6]:
estimator = tf.estimator.LinearRegressor(feature_columns=ft_columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/9c/883h376s53500dcqng4b4nj00000gn/T/tmppbgz65sf', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0xb20fa1d68>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [7]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train, y_test = train_test_split(x_data,y_real,test_size=0.3,random_state=101)

In [9]:
print(x_train)

[6.83743684 5.66519567 3.97899398 ... 4.76497476 2.14539215 1.76991177]


In [10]:
########################################################################################
# ref) https://www.tensorflow.org/api_docs/python/tf/estimator/inputs/numpy_input_fn
# 
# age = np.arange(4) * 1.0
# height = np.arange(32, 36)
# x = {'age': age, 'height': height}
# y = np.arange(-32, -28)

# with tf.Session() as session:
#   input_fn = numpy_io.numpy_input_fn(
#       x, y, batch_size=2, shuffle=False, num_epochs=1)

In [12]:
input_func = tf.estimator.inputs.numpy_input_fn({"x":x_train}, y_train, batch_size=8, num_epochs=None, shuffle=True)

In [13]:
train_func = tf.estimator.inputs.numpy_input_fn({"x":x_train}, y_train, batch_size=8, num_epochs=1000, shuffle=False)

In [14]:
test_func = tf.estimator.inputs.numpy_input_fn({"x":x_test}, y_test, batch_size=8, num_epochs=1000, shuffle=True)

In [17]:
estimator.train(input_fn=train_func, steps= 1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /var/folders/9c/883h376s53500dcqng4b4nj00000gn/T/tmppbgz65sf/model.ckpt-1000
Instructions for updating:
Use standard file utilities to get mtimes.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1000 into /var/folders/9c/883h376s53500dcqng4b4nj00000gn/T/tmppbgz65sf/model.ckpt.
INFO:tensorflow:loss = 5.0608315, step = 1001
INFO:tensorflow:global_step/sec: 602.449
INFO:tensorflow:loss = 3.6601179, step = 1101 (0.167 sec)
INFO:tensorflow:global_step/sec: 703.611
INFO:tensorflow:loss = 12.000345, step = 1201 (0.142 sec)
INFO:tensorflow:global_step/sec: 751.237
INFO:tensorflow:loss = 5.780149, step = 1301 (0.134 sec)
INFO:tensorflow:global_

In [18]:
test_eval = estimator.evaluate(input_fn=test_func, steps=1000)
test_eval

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-04-05T20:10:05Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/9c/883h376s53500dcqng4b4nj00000gn/T/tmppbgz65sf/model.ckpt-2000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [100/1000]
INFO:tensorflow:Evaluation [200/1000]
INFO:tensorflow:Evaluation [300/1000]
INFO:tensorflow:Evaluation [400/1000]
INFO:tensorflow:Evaluation [500/1000]
INFO:tensorflow:Evaluation [600/1000]
INFO:tensorflow:Evaluation [700/1000]
INFO:tensorflow:Evaluation [800/1000]
INFO:tensorflow:Evaluation [900/1000]
INFO:tensorflow:Evaluation [1000/1000]
INFO:tensorflow:Finished evaluation at 2019-04-05-20:10:07
INFO:tensorflow:Saving dict for global step 2000: average_loss = 1.0197684, global_step = 2000, label/mean = 7.4857903, loss = 8.158147, prediction/mean = 7.4502683
INFO:tensorflow:Saving 

{'average_loss': 1.0197684,
 'label/mean': 7.4857903,
 'loss': 8.158147,
 'prediction/mean': 7.4502683,
 'global_step': 2000}

In [19]:
new_data = np.linspace(0,10,100)

In [20]:
# tf.estimator 와 estimator를 햇갈리지 말자
new_data_input_func = tf.estimator.inputs.numpy_input_fn({"x":new_data},shuffle=False) 

In [21]:
estimator.predict(new_data_input_func)

<generator object EstimatorV2.predict at 0x1a25649390>

In [22]:
list(estimator.predict(new_data_input_func))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/9c/883h376s53500dcqng4b4nj00000gn/T/tmppbgz65sf/model.ckpt-2000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([4.8591776], dtype=float32)},
 {'predictions': array([4.9116206], dtype=float32)},
 {'predictions': array([4.964064], dtype=float32)},
 {'predictions': array([5.016507], dtype=float32)},
 {'predictions': array([5.06895], dtype=float32)},
 {'predictions': array([5.1213937], dtype=float32)},
 {'predictions': array([5.1738367], dtype=float32)},
 {'predictions': array([5.2262797], dtype=float32)},
 {'predictions': array([5.2787232], dtype=float32)},
 {'predictions': array([5.3311663], dtype=float32)},
 {'predictions': array([5.38361], dtype=float32)},
 {'predictions': array([5.436053], dtype=float32)},
 {'predictions': array([5.488496], dtype=float32)},
 {'predictions': array([5.5409393], dtype=float32)},
 {'predictions': array([5.5933824], dtype=float32)},
 {'predictions': array([5.6458254], dtype=float32)},
 {'predictions': array([5.698269], dtype=float32)},
 {'predictions': array([5.750712], dtype=float32)},
 {'predictions': array([5.803155], dtype=float32)},
 {'p