In [15]:
import tensorflow as tf
import numpy as np

In [16]:
np.random.seed(101)

In [17]:
tf.set_random_seed(101)

In [18]:
rand_data_a = np.random.uniform(0,100,(10,10))

In [19]:
rand_data_b = np.random.uniform(0,100,(10,1))

In [20]:
rand_data_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817,
        83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224,
        23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261,
        99.43179012, 52.06653967, 57.87895355, 73.48190583, 54.19617722],
       [91.31535577, 80.7920151 , 40.29978307, 35.72243428, 95.28767147,
        34.36315779, 86.50998163, 83.02777122, 53.81614492, 92.24693726],
       [ 9.71464798, 10.28474932, 70.15072957, 89.04798691, 15.95603009,
        27.55725449, 67.24915297, 16.4303124 , 70.13711366, 48.76352222],
       [68.06777682, 52.15481923,  4.33966944, 22.39366035, 57.52050869,
        12.04336601, 50.01167138, 13.80095683,  5.28084011, 17.82769225],
       [44.23681315, 87.75873246, 94.9264129 , 47.81674168, 46.11193423,
        63.7289031 , 32.46079964, 11.7578093 

In [21]:
rand_data_b

array([[69.45646648],
       [34.24567679],
       [41.23905637],
       [23.97909655],
       [96.88359762],
       [28.85570076],
       [14.73116127],
       [12.93404399],
       [94.40560505],
       [35.14342645]])

In [22]:
placeholder_a = tf.placeholder(tf.float32)

In [23]:
placeholder_b = tf.placeholder(tf.float32)

adding = placeholder_a + placeholder_b
multiplying = placeholder_a * placeholder_b


In [30]:
with tf.Session() as sess:
    result = sess.run(adding, feed_dict={placeholder_a:rand_data_a, placeholder_b:rand_data_b})
    result
    

In [31]:
result


array([[121.09633 , 126.523224,  72.30389 ,  86.608635, 137.98416 ,
        152.84616 , 100.15309 , 158.81778 , 141.61086 ,  88.45036 ],
       [ 89.66844 ,  69.45888 ,  52.434917, 112.80585 , 130.794   ,
         57.481045,  42.60182 ,  94.600525, 107.14496 ,  61.86956 ],
       [109.769684,  93.0258  ,  46.08751 ,  55.025978,  59.9358  ,
        140.67085 ,  93.305595,  99.11801 , 114.72096 ,  95.435234],
       [115.29445 , 104.77111 ,  64.27888 ,  59.70153 , 119.26677 ,
         58.342255, 110.489075, 107.00687 ,  77.79524 , 116.226036],
       [106.59824 , 107.16835 , 167.03433 , 185.93158 , 112.83963 ,
        124.44086 , 164.13275 , 113.31391 , 167.02072 , 145.64713 ],
       [ 96.92348 ,  81.01052 ,  33.19537 ,  51.24936 ,  86.376205,
         40.899067,  78.86737 ,  42.65666 ,  34.136543,  46.683395],
       [ 58.96797 , 102.4899  , 109.65758 ,  62.547905,  60.843094,
         78.46007 ,  47.191963,  26.488972,  19.84126 ,  78.497025],
       [ 94.16064 ,  79.96008 ,  78.11082

# </nspr>
# simple neural network step 1

In [59]:
num_features = 10
num_neurons = 3

In [60]:
X = tf.placeholder(tf.float32,(None,num_features))
W = tf.Variable(tf.random_normal([num_features,num_neurons]))

B = tf.Variable(tf.ones([num_neurons]))

print(W)

print(B)


<tf.Variable 'Variable_14:0' shape=(10, 3) dtype=float32_ref>
<tf.Variable 'Variable_15:0' shape=(3,) dtype=float32_ref>


In [72]:
with tf.Session() as sess:
    initializer1 = tf.global_variables_initializer()
    sess.run(initializer1)
    
    XW = tf.matmul(X,W)
    Z = tf.add(XW,B)
    A = tf.sigmoid(Z)
    
    sess.run(W)
    sess.run(B)
    result = sess.run(A, feed_dict ={X:np.random.random((1,num_features))})
    print(tf.sigmoid(Z))
#     print(W)
#     print(B)

    print (result)

Tensor("Sigmoid_6:0", shape=(?, 3), dtype=float32)
[[0.98763907 0.97560966 0.8304962 ]]


In [70]:
W

<tf.Variable 'Variable_14:0' shape=(10, 3) dtype=float32_ref>